## Instagram Data

## Data Ingetsion

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
BASE = '../Data/IGData.xlsx'

df = pd.read_excel(BASE)
df.head(10)

,Tipo,Data,Curtidas,Comentários,Visualizações,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,NaN,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,NaN,Loja/Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,NaN,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,82878.0,Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,NaN,Produtos,S,N,NaN,4437
5,Foto,2021-09-17,5359,62,NaN,Novos Produtos,N,S,S,5421
6,Foto,2021-09-19,21597,852,NaN,Novos Produtos,S,S,NaN,22449
7,Foto,2021-09-25,6346,33,NaN,Produtos,N,S,NaN,6379
8,Foto,2021-09-27,6355,89,NaN,Produtos,S,N,S,6444
9,Vídeo,2021-09-28,4056,81,73174.0,Produtos,N,N,NaN,4137

## Initial EDA

In [3]:
df.shape

(52, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tipo           52 non-null     object
 1   Data           52 non-null     datetime64[ns]
 2   Curtidas       52 non-null     int64
 3   Comentários    52 non-null     int64
 4   Visualizações  15 non-null     float64
 5   Tags           44 non-null     object
 6   Pessoas        52 non-null     object
 7   Campanhas      52 non-null     object
 8   Carrossel      8 non-null      object
 9   Interacoes     52 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 4.2+ KB

In [5]:
df.describe()

,Data,Curtidas,Comentários,Visualizações,Interacoes
count,52,52.000000,52.000000,15.000000,52.000000
mean,2021-12-23 04:36:55.384615424,12262.730769,189.500000,53295.933333,12452.230769
min,2021-09-11 00:00:00,2807.000000,9.000000,12627.000000,2816.000000
25%,2021-10-23 06:00:00,5492.000000,69.500000,23625.000000,5562.500000
50%,2022-01-05 00:00:00,9603.000000,128.000000,67205.000000,9773.500000
75%,2022-02-15 12:00:00,17621.750000,265.250000,71686.000000,17920.750000
max,2022-03-27 00:00:00,37351.000000,852.000000,92120.000000,37853.000000
std,NaN,8165.875326,170.687709,26975.183215,8299.390088

In [6]:
df.describe(include='object')

        Tipo      Tags Pessoas Campanhas Carrossel
count     52        44      52        52         8
unique     4        12       2         2         1
top     Foto  Produtos       S         N         S
freq      36        12      40        30         8

In [7]:
df.isnull().sum()

Tipo              0
Data              0
Curtidas          0
Comentários       0
Visualizações    37
Tags              8
Pessoas           0
Campanhas         0
Carrossel        44
Interacoes        0
dtype: int64

In [8]:
#Separate into categorical and numerical
categorical_columns = [
    'Tags',
    'Pessoas',
    'Campanhas',
    'Carrossel'
]

numerical_columns = [
    'Curtidas',
    'Comentários',
    'Visualizações',
    'Interacoes'
]

In [9]:
for column in categorical_columns:
    print(f"Column: {column}")
    print(df[column].value_counts())
    print()

Column: Tags
Tags
Produtos                             12
Novos Produtos                        7
Influenciadores                       7
Datas comemorativas                   3
Dicas de como usar/Produtos           3
Trends                                3
Dicas de como usar/Novos Produtos     2
Loja                                  2
Promoções                             2
Loja/Produtos                         1
Trends/Produtos                       1
Datas comemorativas/Promoções         1
Name: count, dtype: int64

Column: Pessoas
Pessoas
S    40
N    12
Name: count, dtype: int64

Column: Campanhas
Campanhas
N    30
S    22
Name: count, dtype: int64

Column: Carrossel
Carrossel
S    8
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tipo           52 non-null     object
 1   Data           52 non-null     datetime64[ns]
 2   Curtidas       52 non-null     int64
 3   Comentários    52 non-null     int64
 4   Visualizações  15 non-null     float64
 5   Tags           44 non-null     object
 6   Pessoas        52 non-null     object
 7   Campanhas      52 non-null     object
 8   Carrossel      8 non-null      object
 9   Interacoes     52 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 4.2+ KB

In [11]:
print(df.duplicated().sum())

0

In [12]:
df.nunique()

Tipo              4
Data             50
Curtidas         52
Comentários      49
Visualizações    15
Tags             12
Pessoas           2
Campanhas         2
Carrossel         1
Interacoes       52
dtype: int64

In [13]:
df['Tags'].isnull().sum()

np.int64(8)

## Basic Data Cleaning

### General Orientations
 - Understant where is the best engagement
 - Empty tags should be treated as empty
 - Ignore Visualization

In [14]:
# Renaming the columns from Portuguse to English
translation = {
    'Tipo':'Type',
    'Data':'Date',
    'Curtidas':'Likes',
    'Comentários': 'Comments',
    'Visualizações':'Views',
    'Pessoas':'People',
    'Campanhas': 'Campaign',
    'Carrossel':'Carousel',
    'Interacoes ':'Interactions',
}

In [15]:
df = df.rename(columns=translation)
df.head()

,Type,Date,Likes,Comments,Views,Tags,People,Campaign,Carousel,Interactions
0,Foto,2021-09-11,2858,16,NaN,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,NaN,Loja/Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,NaN,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,82878.0,Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,NaN,Produtos,S,N,NaN,4437

In [16]:
#Separate into categorical and numerical
categorical_columns = [
    'Tags',
    'People',
    'Campaign',
    'Carousel'
]

numerical_columns = [
    'Likes',
    'Comments',
    'Interactions'
]

In [17]:
#As requested in the exercise, we need to drop the vizual;isation column
df = df.drop(columns='Views')
df.head()

,Type,Date,Likes,Comments,Tags,People,Campaign,Carousel,Interactions
0,Foto,2021-09-11,2858,16,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,Loja/Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,Produtos,S,N,NaN,4437

In [18]:
# Insert data in Carousel column
df.loc[(df['Carousel'].isnull(), 'Carousel')] = 'N'

In [19]:
df['Carousel'].value_counts()

Carousel
N    44
S     8
Name: count, dtype: int64

In [20]:
df.isnull().sum()

Type            0
Date            0
Likes           0
Comments        0
Tags            8
People          0
Campaign        0
Carousel        0
Interactions    0
dtype: int64

In [21]:
df.loc[df['Tags'].isnull(), 'Tags'] = 'Sem Tags'

In [22]:
df['Tags'].value_counts()

Tags
Produtos                             12
Sem Tags                              8
Novos Produtos                        7
Influenciadores                       7
Datas comemorativas                   3
Dicas de como usar/Produtos           3
Trends                                3
Loja                                  2
Promoções                             2
Dicas de como usar/Novos Produtos     2
Loja/Produtos                         1
Trends/Produtos                       1
Datas comemorativas/Promoções         1
Name: count, dtype: int64

In [23]:
for column in categorical_columns:
    df[column] = df[column].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          52 non-null     object
 1   Date          52 non-null     datetime64[ns]
 2   Likes         52 non-null     int64
 3   Comments      52 non-null     int64
 4   Tags          52 non-null     category
 5   People        52 non-null     category
 6   Campaign      52 non-null     category
 7   Carousel      52 non-null     category
 8   Interactions  52 non-null     int64
dtypes: category(4), datetime64[ns](1), int64(3), object(1)
memory usage: 3.4+ KB

## Key point Analysis

In [24]:
df.head()

,Type,Date,Likes,Comments,Tags,People,Campaign,Carousel,Interactions
0,Foto,2021-09-11,2858,16,Loja,N,N,N,2874
1,Foto,2021-09-11,2930,28,Loja/Produtos,N,N,N,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,N,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,N,5164
4,Foto,2021-09-13,4392,45,Produtos,S,N,N,4437

In [25]:
df.groupby('Type').size().sort_values(ascending=False)

Type
Foto     36
Vídeo     6
IGTV      5
Reels     5
dtype: int64

In [26]:
df.groupby('Type')[['Likes','Comments','Interactions']].mean().sort_values(by='Likes', ascending=False)

              Likes    Comments  Interactions
Type
Reels  14873.000000  244.400000  15117.400000
Foto   13341.138889  193.416667  13534.555556
Vídeo   8141.500000  166.833333   8308.333333
IGTV    6833.400000  133.600000   6967.000000

In [27]:
df_subframe = df.loc[df['Type'] != 'Foto']
df_subframe

,Type,Date,Likes,Comments,Tags,People,Campaign,Carousel,Interactions
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,N,5164
9,Vídeo,2021-09-28,4056,81,Produtos,N,N,N,4137
10,Reels,2021-10-10,12894,249,Trends/Produtos,S,N,N,13143
15,Vídeo,2021-11-04,3646,71,Produtos,N,N,N,3717
16,Reels,2021-11-06,6376,137,Produtos,N,N,N,6513
17,Vídeo,2021-11-09,3213,60,Produtos,N,N,N,3273
18,Reels,2021-11-12,5493,59,Produtos,N,N,N,5552
24,Vídeo,2021-12-30,17600,383,Trends,S,S,N,17983
30,Reels,2022-01-24,29981,502,Trends,S,S,N,30483
32,IGTV,2022-02-04,9270,222,Dicas de como usar/Produtos,S,N,N,9492
35,IGTV,2022-02-10,8556,188,Dicas de como usar/Produtos,S,N,N,8744
37,Vídeo,2022-02-13,15219,357,Datas comemorativas,S,S,N,15576
44,IGTV,2022-03-07,5918,116,Dicas de como usar/Novos Produtos,S,N,N,6034
45,Reels,2022-03-08,19621,275,Trends,S,S,N,19896
47,IGTV,2022-03-12,5489,77,Dicas de como usar/Novos Produtos,S,N,N,5566
51,IGTV,2022-03-27,4934,65,Dicas de como usar/Produtos,S,N,N,4999

In [28]:
df_subframe.groupby('Type')[['Likes','Comments','Interactions']].mean().sort_values(by='Likes', ascending=False)

         Likes    Comments  Interactions
Type
Reels  14873.0  244.400000  15117.400000
Vídeo   8141.5  166.833333   8308.333333
IGTV    6833.4  133.600000   6967.000000

In [29]:
df[['Date','Type']].value_counts()

Date        Type
2021-09-11  Foto     3
2021-09-12  Vídeo    1
2021-09-13  Foto     1
2021-09-17  Foto     1
2021-09-19  Foto     1
2021-09-25  Foto     1
2021-09-27  Foto     1
2021-09-28  Vídeo    1
2021-10-10  Reels    1
2021-10-12  Foto     1
2021-10-21  Foto     1
2021-10-24  Foto     1
2021-10-29  Foto     1
2021-11-04  Vídeo    1
2021-11-06  Reels    1
2021-11-09  Vídeo    1
2021-11-12  Reels    1
2021-12-12  Foto     1
2021-12-16  Foto     1
2021-12-23  Foto     1
2021-12-26  Foto     1
2021-12-28  Foto     1
2021-12-30  Vídeo    1
2022-01-02  Foto     1
2022-01-08  Foto     1
2022-01-11  Foto     1
2022-01-15  Foto     1
2022-01-19  Foto     1
2022-01-24  Reels    1
2022-01-27  Foto     1
2022-02-04  IGTV     1
2022-02-06  Foto     1
2022-02-09  Foto     1
2022-02-10  IGTV     1
2022-02-12  Foto     1
2022-02-13  Vídeo    1
2022-02-15  Foto     1
2022-02-17  Foto     1
2022-02-21  Foto     1
2022-02-22  Foto     1
2022-02-26  Foto     1
2022-03-04  Foto     1
2022-03-07  IGTV     1
2022-03-08  Reels    1
2022-03-09  Foto     1
2022-03-12  IGTV     1
2022-03-20  Foto     1
2022-03-22  Foto     1
2022-03-26  Foto     1
2022-03-27  IGTV     1
Name: count, dtype: int64

In [45]:
# It's possible to see more interaction with Photos and Reels, Although photos are more frequent, lately, this person
# has beend doing more IGTV than Reels. Unless they want to migrate to be an IGTV influence, the preference should be Photos and Reels
pd.crosstab(df['Type'],df['People'])

People  N   S
Type
Foto    6  30
IGTV    0   5
Reels   2   3
Vídeo   4   2

In [ ]:
df.pivot_table(
    index=['Type'],
    columns='Campaign',
    values='Likes',
    aggfunc=['size','sum']
)

C:\Users\satos\AppData\Local\Temp\ipykernel_35144\1558575159.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(
C:\Users\satos\AppData\Local\Temp\ipykernel_35144\1558575159.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(

         size         sum
Campaign    N   S       N       S
Type
Foto       18  18  162890  317391
IGTV        5   0   34167       0
Reels       3   2   24763   49602
Vídeo       4   2   16030   32819

In [86]:
df.groupby('Tags')['Likes'].mean()

C:\Users\satos\AppData\Local\Temp\ipykernel_35144\246340871.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Tags')['Likes'].mean()

Tags
Datas comemorativas                  17975.000000
Datas comemorativas/Promoções        29084.000000
Dicas de como usar/Novos Produtos     5703.500000
Dicas de como usar/Produtos           7586.666667
Influenciadores                      15197.285714
Loja                                  2832.500000
Loja/Produtos                         2930.000000
Novos Produtos                       11619.571429
Produtos                              5666.916667
Promoções                            26645.500000
Sem Tags                             15347.875000
Trends                               22400.666667
Trends/Produtos                      12894.000000
Name: Likes, dtype: float64

In [95]:
df.pivot_table(
    index=['Type'],
    columns='People',
    values='Likes',
    aggfunc=['size','sum', 'mean']
)

C:\Users\satos\AppData\Local\Temp\ipykernel_35144\3729252405.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(
C:\Users\satos\AppData\Local\Temp\ipykernel_35144\3729252405.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(
C:\Users\satos\AppData\Local\Temp\ipykernel_35144\3729252405.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(

       size        sum            mean
People    N   S      N       S       N             S
Type
Foto      6  30  23181  457100  3863.5  15236.666667
IGTV      0   5      0   34167     NaN   6833.400000
Reels     2   3  11869   62496  5934.5  20832.000000
Vídeo     4   2  16030   32819  4007.5  16409.500000